<?php require_once '../config/database.php'; require_once '../includes/session.php'; require_admin();
$data=[
 'users'=>$pdo->query('SELECT COUNT(*) FROM users')->fetchColumn(),
 'products'=>$pdo->query('SELECT COUNT(*) FROM products')->fetchColumn(),
 'orders'=>$pdo->query('SELECT COUNT(*) FROM orders')->fetchColumn(),
 'sales'=>$pdo->query('SELECT COALESCE(SUM(total_amount),0) FROM orders')->fetchColumn(),
 'reviews'=>$pdo->query('SELECT COUNT(*) FROM product_reviews')->fetchColumn(),
 'wishlist'=>$pdo->query('SELECT COUNT(*) FROM wishlists')->fetchColumn(),
];
$orders=$pdo->query('SELECT o.*, u.name AS user_name FROM orders o JOIN users u ON u.id=o.user_id ORDER BY o.created_at DESC LIMIT 8')->fetchAll();
$top=$pdo->query('SELECT p.name, SUM(oi.quantity) sold FROM order_items oi JOIN products p ON p.id=oi.product_id GROUP BY p.id ORDER BY sold DESC LIMIT 5')->fetchAll();
?>
<!DOCTYPE html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin Dashboard</title><link rel="stylesheet" href="../css/bootstrap.css"><link rel="stylesheet" href="../css/complex.css"><link rel="stylesheet" href="../css/liquid-glass.css"><link rel="stylesheet" href="../css/professional.css"><link rel="stylesheet" href="../css/professional.css"></head><body><div class="admin-shell"><aside class="admin-sidebar glass-card"><h4>Admin Panel</h4><a href="../index.php">Lihat Website</a><a href="dashboard.php">Dashboard</a><a href="products_manage.php">Kelola Produk</a><a href="categories_manage.php">Kelola Kategori</a><a href="coupons_manage.php">Kelola Kupon</a><a href="orders_manage.php">Kelola Pesanan</a><a href="../auth/logout.php">Logout</a></aside><main class="admin-main"><div class="glass-panel mb-4"><h2 class="section-title">Dashboard Admin</h2><p class="section-subtitle">Ringkasan transaksi, pelanggan, produk, wishlist, dan ulasan.</p></div><div class="row"><div class="col-md-4 col-xl-2 mb-3"><div class="glass-card metric"><h3><?= $data['users'] ?></h3><p>User</p></div></div><div class="col-md-4 col-xl-2 mb-3"><div class="glass-card metric"><h3><?= $data['products'] ?></h3><p>Produk</p></div></div><div class="col-md-4 col-xl-2 mb-3"><div class="glass-card metric"><h3><?= $data['orders'] ?></h3><p>Pesanan</p></div></div><div class="col-md-4 col-xl-2 mb-3"><div class="glass-card metric"><h3><?= $data['reviews'] ?></h3><p>Review</p></div></div><div class="col-md-4 col-xl-2 mb-3"><div class="glass-card metric"><h3><?= $data['wishlist'] ?></h3><p>Wishlist</p></div></div><div class="col-md-4 col-xl-2 mb-3"><div class="glass-card metric"><h3>Rp <?= number_format($data['sales'],0,',','.') ?></h3><p>Omzet</p></div></div></div><div class="row mt-4"><div class="col-lg-8 mb-3"><div class="glass-card p-4"><h4>Pesanan Terbaru</h4><div class="table-responsive"><table class="table"><tr><th>Invoice</th><th>Customer</th><th>Total</th><th>Status</th></tr><?php foreach($orders as $o): ?><tr><td><?= htmlspecialchars($o['invoice_code']) ?></td><td><?= htmlspecialchars($o['user_name']) ?></td><td>Rp <?= number_format($o['total_amount'],0,',','.') ?></td><td><span class="status-pill"><?= $o['status'] ?></span></td></tr><?php endforeach; ?></table></div></div></div><div class="col-lg-4"><div class="glass-card p-4"><h4>Produk Terlaris</h4><?php foreach($top as $t): ?><p class="d-flex justify-content-between border-bottom pb-2"><span><?= htmlspecialchars($t['name']) ?></span><b><?= (int)$t['sold'] ?></b></p><?php endforeach; if(!$top): ?><p>Belum ada penjualan.</p><?php endif; ?></div></div></div></main></div></body></html>
